title: Vennisa Owusu-Barfi
logo: https://github.com/vennisabarfi/vennisabarfi/assets/122574563/babef36b-f7db-4105-93b0-a9ce3bc9dc69 
description: Passionate about Data and Deep Learning
show_downloads: true
theme: jekyll-theme-minimal #look up different themes on github themes to change
