title: Vennisa Owusu-Barfi
logo: /assets/img/"C:\Users\veyhn\Downloads\IMG-7730.jpg"
description: Passionate about Data and Deep Learning
show_downloads: true
theme: jekyll-theme-minimal #look up different themes on github themes to change
