title: Vennisa Owusu-Barfi
#logo: /assets/img/headshot_circle.png
description: Passionate about Data and Deep Learning
show_downloads: true
theme: jekyll-theme-minimal #look up different themes on github themes to change
